// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://snyebxiwwjaylbckieft.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNueWVieGl3d2pheWxiY2tpZWZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk2MDY2MDcsImV4cCI6MjA1NTE4MjYwN30.YuWA4LME5kNJp-LLRiOXn40-4ThlHpjy7cgDbA8DB8c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);